### ISSUE TITLE
Help me with mobile responsiveness

### ISSUE THREAD

**Issue by prinsi-t** [prinsi-t/Pets-webpage#1]
I'm having trouble making this website mobile responsive, if you could help me with that it would be great!

![Screenshot (297)](https://github.com/prinsi-t/Pets-webpage/assets/116324634/3950c118-4796-498e-ae69-b85d2b4af652)

![Screenshot (301)](https://github.com/prinsi-t/Pets-webpage/assets/116324634/560861da-090a-4e28-9325-4ef80994823c)

![Screenshot (295)](https://github.com/prinsi-t/Pets-webpage/assets/116324634/187d49cf-cac4-4ff6-8ec2-fd213408eebe)

**Comment by AnukratiMehta** [comment]
@prinsi-t I can help you with this.

**Comment by prinsi-t** [comment]
oh thanks i would love ur help!

**Comment by prinsi-t** [comment]
@AnukratiMehta thanks it would be great!

**Comment by Anmol-Gup** [comment]
Hi @prinsi-t , I have tried to make this responsive. I am attaching video.


https://github.com/prinsi-t/Pets-webpage/assets/66009201/597360a3-fb19-4d75-88c3-35f96fab8603

**Comment by prinsi-t** [comment]
@Anmol-Gup thank you it looks good ! can u please also make that blue background white? it would be great.
nd send me pr then thanks again.

**Comment by prinsi-t** [comment]
@Anmol-Gup thanks Anmol its  all working very well now appreciate it!
